# ----
# Site

title: Programavimas kalba Java
display_title: Lekt. M. Gžegoževskis
url: "https://eif-courses.github.io/java"
baseurl: /java
google_analytics_key: UA-80995145-2
show_full_navigation: false

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Documentation for CloudCannon, the Cloud CMS for Jekyll.
social:
  name: eif-COURSES
  links:
    - https://www.facebook.com/vikoeif
twitter:
  username: CloudCannon

# -----
# Build

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      image: /siteicon.png
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      layout: doc
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major

builds:
  - Any
  - Static
  - Jekyll

plans:
  - Free
  - Basic
  - Pro

hostings:
  - Any
  - CloudCannon
